name: Generate GitHub Snake

on:
  workflow_dispatch: {}     # manual run
  schedule:
    - cron: '0 0 * * *'     # optional daily run (UTC). Remove if you don't want scheduled runs.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          # optional: set w/h or colors here if the action supports inputs
          outputs: dist

      - name: Prepare output branch
        run: |
          mkdir -p dist
          # Platane/snk writes to dist by default; ensure it's present
          ls -la dist || true

      - name: Commit and push to output branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update snake"
          branch: output
          file_pattern: dist/**
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
